#!/bin/bash
AA="$"
KK="$"KIT_PATH
PP="$"PATH
QQ="$"DFT_BIN
BB="$"BGW_BIN
TT="$"tools_bin
##########In the following, you can set as default##############
export use_poscar=.True.                   #using POSCAR in format of VASP to get the cell file

##########You must set the following enivronmental varies ##############
module load compiler/intel/2017_up7
export KIT_PATH=/home/jiafanhao/software/bin/qe_bgw_kit
export tools_bin=/home/jiafanhao/software/bin/qe_bgw_kit/bin
export BGW_BIN=/share/opt/apps/BGW/1.0.4-2d-3p/bin
export DFT_BIN=/share/opt/apps/paratec_MKL_pz/bin

pseudo_dir=/home/jiafanhao/work/MXene/paratec/pot
export PATH=/usr/bin:$PATH
export PATH=/share/opt/miniconda3/bin:$PATH
